### ISSUE TITLE
Compression feature allocates lots of memory when decompressing both low and high entropy data

### ISSUE THREAD

**Issue by Mrmaxmeier** [spacejam/sled#938] opened 2020-01-26 15:40 UTC
Hey there,

I'm seeing OOMs due to very large allocations when using the compression feature. (Linux, `sled 0.30.3`, `rustc 1.42.0-nightly (2020-01-24)`).

This example should reproduce the issue:
```console
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/sled_repro`
reloading database...
memory allocation of 112879763444 bytes failedAborted (core dumped)
```

```rust
fn main() {
    let low_entropy = vec![0u8; 64 << 10]; // 64k zeroes
    let high_entropy = {                   // 64mb random
        use std::fs::File;
        use std::io::Read;
        let mut buf = vec![0u8; 64 << 20];
        File::open("/dev/urandom")
            .unwrap()
            .read_exact(&mut buf)
            .unwrap();
        buf
    };

    let tree = sled::Config::default()
        .use_compression(true)
        .path("test.sled")
        .open()
        .unwrap();

    tree.insert(b"low  entropy", &low_entropy[..]).unwrap();
    tree.insert(b"high entropy", &high_entropy[..]).unwrap();

    println!("reloading database...");
    drop(tree);
    let _ = sled::Config::default()
        .use_compression(true)
        .path("test.sled")
        .open()
        .unwrap();
}
```

This panicks on my machine because it's trying to decompress the 64Mb random blob into a buffer of size `MAX_COMPRESSION_RATIO` * 64Mb. The low entropy blob bumps `MAX_COMPRESSION_RATIO` up to > 1000 and thus `decompress_maybe` tries to allocate >100Gb. Here's the relevant code: https://github.com/spacejam/sled/blob/68162d219e29a9572762d3246450f7dbe72c0b41/src/pagecache/mod.rs#L259-L277

Note: I'm using this patch as a workaround:

```diff
diff --git a/src/pagecache/mod.rs b/src/pagecache/mod.rs
index 8aa7d54f..451d1c0a 100644
--- a/src/pagecache/mod.rs
+++ b/src/pagecache/mod.rs
@@ -259,8 +259,8 @@ pub(crate) fn maybe_decompress(buf: Vec<u8>) -> std::io::Result<Vec<u8>> {
         static MAX_COMPRESSION_RATIO: AtomicUsize = AtomicUsize::new(1);
 
         let _measure = Measure::new(&M.decompress);
+        let mut ratio = MAX_COMPRESSION_RATIO.load(Acquire);
         loop {
-            let ratio = MAX_COMPRESSION_RATIO.load(Acquire);
             match decompress(&*buf, buf.len() * ratio) {
                 Err(ref e) if e.kind() == std::io::ErrorKind::Other => {
                     debug!(
@@ -270,11 +270,15 @@ pub(crate) fn maybe_decompress(buf: Vec<u8>) -> std::io::Result<Vec<u8>> {
                         ratio + 1,
                         e
                     );
-                    let _who_cares = MAX_COMPRESSION_RATIO.compare_and_swap(
-                        ratio,
-                        ratio + 1,
-                        Release,
-                    );
+                    // is this ratio reasonable as a default for other
+                    // decompressions?
+                    if ratio < 10 {
+                        let _who_cares = MAX_COMPRESSION_RATIO
+                            .compare_and_swap(ratio, ratio + 1, Release);
+                        ratio += 1;
+                    } else {
+                        ratio *= 2;
+                    }
                 }
                 other => return other,
             }

```

**Comment by spacejam** [comment] 2020-01-27 09:37
Hey @Mrmaxmeier, thank you for opening this issue and including the excellent breakdown :) 

This is also quite well timed, because on [my `tyler_iobuf_refactoring` branch](/spacejam/sled/tree/tyler_iobuf_refactoring) I'm rewriting some big chunks of the read and write paths.

But, I think this one might actually be quite simple to fix. By using zstd's streaming decode functionality instead, under the hood it will rely on Vec's Write implementation that basically just calls `extend_from_slice` over and over. This is less ideal than just guessing the correct buffer size up-front, but it seems doing so causes issues like the one you're facing, and I don't want to spend more time on creating a "better" non-linear dynamic buffer sizer. Compression is a time-space trade-off anyway, so I'm OK with using this for now. 

This work is on the current master branch, which breaks compatibility with the latest release. However, if you are able to reproduce your workload using this patch, I would be grateful to know if it completely addresses your issue or not.

**Comment by spacejam** [comment] 2020-01-27 09:39
Oh wait, I can just run exactly the reproduction code you already posted - sorry, still waking up xD

Let me run that now.

**Comment by spacejam** [comment] 2020-01-27 09:42
Confirmed, it aborts without this patch, and runs fine with it :) Thank you for including that nice reproduction code along with your analysis! I'm going to close this issue for now, because I believe it addresses the issue you're seeing, but please let me know if you continue to experience any issues with your own workloads!

**Closed by spacejam** 2020-01-27 09:42 UTC

**Comment by spacejam** [comment] 2020-01-27 09:56
Added this code to a test to prevent regressions in #940
